apiVersion: v1
entries:
  kserve:
  - apiVersion: v1
    created: "2024-10-04T12:56:55.465779-07:00"
    description: Helm chart for deploying kserve resources
    digest: 7b209a0f23af67449b4b62f332651ee44c742bf6592a6f165abbb44e603f68f9
    keywords:
    - kserve
    - modelmesh
    name: kserve
    sources:
    - http://github.com/kserve/kserve
    urls:
    - https://johnliu25.github.io/helm-charts/charts/kserve-v0.14.0-rc0.tgz
    version: v0.14.0-rc0
  kserve-crd:
  - apiVersion: v1
    created: "2024-10-04T12:56:55.462684-07:00"
    description: Helm chart for deploying kserve crds
    digest: 4eedc055a9ac6eb28650557c9751434c55cd17d5962d2395aba4076e7aea28c7
    keywords:
    - kserve
    - modelmesh
    name: kserve-crd
    sources:
    - http://github.com/kserve/kserve
    urls:
    - https://johnliu25.github.io/helm-charts/charts/kserve-crd-v0.14.0-rc0.tgz
    version: v0.14.0-rc0
generated: "2024-10-04T12:56:55.452686-07:00"
